LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

ifeq ($(PB_OFFICIAL),true)
    LOCAL_CFLAGS += -DPB_MAIN_BUILD='"-OFFICIAL"'
else ifeq ($(BETA_BUILD),true)
    LOCAL_CFLAGS += -DPB_MAIN_BUILD='"-BETA"'
else
    LOCAL_CFLAGS += -DPB_MAIN_BUILD='"-UNOFFICIAL"'
endif

LOCAL_SRC_FILES:= \
	orscmd.cpp
LOCAL_CFLAGS += -c -W
LOCAL_MODULE := orscmd
LOCAL_MODULE_STEM := twrp
LOCAL_MODULE_TAGS:= optional
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_PACK_MODULE_RELOCATIONS := false
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
include $(BUILD_EXECUTABLE)
